name: F# build and tests

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build
        run: for file in $(find . -name "*.sln"); do dotnet build $file; done
      
      - name: Run tests
        run: for file in $(find . -name "*.sln"); do dotnet test $file; done
